apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: htk-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "hive-test-kube-ip"
spec:
  defaultBackend:
    service:
      name: jenkins2
      port:
        number: 8080
