apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: htk-jenkins
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: htk-jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: htk-jenkins
    spec:
      securityContext:
        fsGroup: 1000
      #nodeSelector:
      #  type: core
      serviceAccountName: jenkins
      containers:
      - name: master
        image: kgyrtkirk/htk-jenkins
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 12000Mi
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
          - mountPath: "/var/jenkins_home"
            name: jenkins-home
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-data3
