---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - namespaces
  verbs: ["list", "watch", "create", "delete", "update"]
- apiGroups: ["*","","serving.knative.dev", "autoscaling.internal.knative.dev", "networking.internal.knative.dev"]
  resources: ["*", "*/status", "*/finalizers"]
  verbs: ["get", "list", "create", "update", "delete", "deletecollection", "patch", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/finalizers"] # finalizers are needed for the owner reference of the webhook
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["workflows", "workflows/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apps","pvc","pv"]
  resourceNames:
  - apps
  - hive-test-kube
  - kubernetes.io/pvc-protection
  resources:
  - kubernetes.io/pvc-protection
  - pvc/finalizers
  - finalizers
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  - pvcs
  - persistentvolumes
  - persistentvolumeclaims
  resources:
    - pvcs/finalizers
    - deployments/finalizers
  verbs:
    - update
- apiGroups:
  - apps
  resources:
    - deployments/finalizers
    - services/finalizers
    - hive-text-kube/finalizers
    - finalizers
  verbs:
    - update
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - jenkins
  - pvc-role
  verbs:
  - "update"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pvc-htk-jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvc-role
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: hive-test-kube
