#!/bin/bash -e

if [ ! -s /var/jenkins_home/config.xml ];then
	echo " @ setting jenkins defaults"
	cp -r /var/jenkins_home_default/./ /var/jenkins_home/
fi
export JAVA_OPTS+=" -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout=60"

if [ "$1" == "" ];then
	exec /sbin/tini -- /usr/local/bin/jenkins.sh
else
	exec "$@"
fi
